environment:
  global:
    PROJECT_NAME: rust-derivative
  matrix:
    - TARGET: i686-pc-windows-gnu
      MSYS2_BITS: 32
    - TARGET: i686-pc-windows-msvc
      MSYS2_BITS: 32
    - TARGET: x86_64-pc-windows-gnu
      MSYS2_BITS: 64
    - TARGET: x86_64-pc-windows-msvc
      MSYS2_BITS: 64

configuration:
  - 1.15.0  # Minimum supported version
  - stable
  - nightly
  - beta

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CONFIGURATION%
  # Some toolchains don't ship clippy, so handle this case to not break the build
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\Users\appveyor\.rustup\toolchains\%CONFIGURATION%-%TARGET%\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  # Only install `clippy` for 64-bit targets; for reasoning see
  # <https://github.com/rust-lang-nursery/rust-clippy/issues/3202#issuecomment-431641932>
  - if not %CONFIGURATION% == "1.15.0" if %MSYS2_BITS% == "64" rustup component add clippy-preview && set HAS_CLIPPY=y
  - rustc -V
  - cargo -V
  - if defined HAS_CLIPPY cargo clippy -V

build: false

test_script:
  - if %CONFIGURATION% == "nightly" set FEATURES="--features=test-nightly" else set FEATURES=
  - cargo build --verbose %FEATURES%
  - cargo test --verbose %FEATURES%
  - if defined HAS_CLIPPY cargo clippy --verbose %FEATURES%
