[package]
name = "derivative"
version = "0.0.1"
authors = ["mcarton <cartonmartin+git@gmail.com>"]
license = "MIT/Apache-2.0"
documentation = "https://mcarton.github.io/rust-derivative/"
repository = "https://github.com/mcarton/rust-derivative"

[lib]
rustc-macro = true

[dependencies]
quote = "^0.2"
syn = { version = "0.8", features = ["aster", "full", "visit"] }

[dev-dependencies]
compiletest_rs = "^0.2"
